movielen:
  target: dev
  outputs:
    dev:
      dataset: movielen
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /opt/airflow/dags/supports/bigquery_credentials.json
      location: US
      method: service-account
      priority: interactive
      project: pseudo-389406
      threads: 1
      type: bigquery